export const workData = [
    {
        id: "we01",
        num: "01",
        companyName: "Ridown Technology",
        employmentType: "Full Time",
        companyUrl: "",
        location: "Gurugram, Hariyana",
        stDate: "Mar, 2025",
        endDate: "Present",
        shortDescription: "Built their Full Stack Applications from scratch. Used PHP, Laravel, Livewire, JavaScript, Bootstrap",
        longDescription: "",
        companyLink: 'https://www.ridown.com/'
    },
    {
        id:"we02",
        num:"02",
        companyName:"Wemonde Pvt. Ltd.",
        employmentType:"Full Time",
        companyUrl:"",
        location:"Dwarka, New Delhi",
        stDate:"Jul, 2023",
        endDate: "Jan, 2025",
        shortDescription:"Built their front end from scratch. Used NextJS, ReactJS, JavaScript, TypeScript, Bootstrap",
        longDescription:"",
        companyLink: 'https://wemonde.com/'
    },
    {
        id: "we03",
        num: "03",
        companyName: "Jyotishi Pvt. Ltd.",
        employmentType: "Freelance",
        companyUrl: "",
        location: "New Delhi, Delhi",
        stDate: "Jun, 2023",
        endDate: "Jul, 2023",
        shortDescription: "Built their front end from scratch. Used NextJS, ReactJS, JavaScript, TypeScript, Bootstrap",
        longDescription: "",
        companyLink: ''
    },
    {
        id: "we04",
        num: "04",
        companyName: "MITYUNG Infotech",
        employmentType: "Full Time",
        companyUrl: "",
        location: "Noida, Uttar Pradesh",
        stDate: "Mar, 2022",
        endDate: "Jun, 2023",
        shortDescription: "Built their front end from scratch. Used NextJS, ReactJS, JavaScript, TypeScript, Bootstrap",
        longDescription: "",
        companyLink: 'https://mityung.com/'
    },
    {
        id: "we05",
        num: "05",
        companyName: "Fristo Pvt. Ltd.",
        employmentType: "Part Time",
        companyUrl: "",
        location: "New Delhi, Delhi",
        stDate: "Aug, 2021",
        endDate: "Feb, 2022",
        shortDescription: "Built their front end from scratch. Used NextJS, ReactJS, JavaScript, TypeScript, Bootstrap",
        longDescription: "",
        companyLink: ''
    },
]